import {
  BenefitProgram,
  BenefitCategory,
  RuleType,
  RuleOperator,
} from '@/types/benefit';
import { DocumentType } from '@/types/document';
import { getMonthlyFPL } from '../constants/federalLimits2026';
import { AssistanceLevel } from '@/types/quiz';

// ============================================
// TEXAS STATE PROGRAMS (25+ NEW PROGRAMS)
// ============================================

// Texas Vocational Rehabilitation (TWC)
export const TX_VOCATIONAL_REHAB: BenefitProgram = {
  id: 'tx-voc-rehab-2026',
  name: 'Texas Vocational Rehabilitation Services',
  shortName: 'TX VR Services',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free job training, career counseling, assistive technology, and employment support for Texans with disabilities',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 4,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have a disability that creates barriers to employment',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
  ],
  applicationUrl: 'https://www.twc.texas.gov/programs/vocational-rehabilitation',
  helplinePhone: '1-800-628-5115',
};

// Texas CHIP (Children's Health Insurance Program)
export const TX_CHIP: BenefitProgram = {
  id: 'tx-chip-2026',
  name: 'Texas CHIP (Children\'s Health Insurance)',
  shortName: 'TX CHIP',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Low-cost health coverage for uninsured children including doctor visits, prescriptions, dental, vision, and mental health',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 2,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.hasChildren',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have children under 19',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 200),
      weight: 0.9,
      isMandatory: true,
      failureMessage: 'Income must be at or below 200% of federal poverty level',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.PROOF_OF_INCOME,
    DocumentType.BIRTH_CERTIFICATE,
  ],
  applicationUrl: 'https://www.yourtexasbenefits.com/',
  helplinePhone: '1-877-543-7669',
};

// Texas CEAP (Comprehensive Energy Assistance Program)
export const TX_CEAP: BenefitProgram = {
  id: 'tx-ceap-2026',
  name: 'Texas Comprehensive Energy Assistance Program',
  shortName: 'TX CEAP',
  category: BenefitCategory.UTILITIES,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Help with electric and gas bills, plus repairs to heating/cooling systems for low-income Texans',
  estimatedMonthlyValue: 500,
  processingTimeWeeks: 3,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 150),
      weight: 0.9,
      isMandatory: true,
      failureMessage: 'Income must be at or below 150% of federal poverty level',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 0.5,
      isMandatory: false,
      failureMessage: 'Priority given to households with disabled or elderly members',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.tdhca.texas.gov/comprehensive-energy-assistance-program-ceap',
  helplinePhone: '1-877-399-8939',
};

// Texas HCS Waiver (Home and Community-based Services)
export const TX_HCS_WAIVER: BenefitProgram = {
  id: 'tx-hcs-waiver-2026',
  name: 'Texas HCS Waiver (Home & Community-based Services)',
  shortName: 'TX HCS Waiver',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Services for people with intellectual disabilities to live in home or small group settings instead of institutions',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 52,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have an intellectual disability or related condition',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.needsAssistance',
      operator: RuleOperator.INCLUDES,
      value: [AssistanceLevel.SOME, AssistanceLevel.EXTENSIVE],
      weight: 0.8,
      isMandatory: true,
      failureMessage: 'Must need ICF/IID level of care',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/disability/intellectual-or-developmental-disabilities-idd-services',
  helplinePhone: '1-877-438-5658',
};

// Texas CLASS Waiver (Community Living Assistance and Support Services)
export const TX_CLASS_WAIVER: BenefitProgram = {
  id: 'tx-class-waiver-2026',
  name: 'Texas CLASS Waiver (Community Living Assistance)',
  shortName: 'TX CLASS',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Home care, therapies, and support for people with related conditions like cerebral palsy or spina bifida',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 52,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have a related condition that began before age 22',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/disability/intellectual-or-developmental-disabilities-idd-services',
  helplinePhone: '1-877-438-5658',
};

// Texas DBMD Waiver (Deaf Blind with Multiple Disabilities)
export const TX_DBMD_WAIVER: BenefitProgram = {
  id: 'tx-dbmd-waiver-2026',
  name: 'Texas DBMD Waiver (Deaf-Blind with Multiple Disabilities)',
  shortName: 'TX DBMD',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Services for people who are deaf-blind with an additional disability, including therapies, adaptive aids, and respite',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 52,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be deaf-blind with at least one additional disability',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/providers/long-term-care-providers/deaf-blind-multiple-disabilities-dbmd',
  helplinePhone: '1-877-438-5658',
};

// Texas MDCP (Medically Dependent Children Program)
export const TX_MDCP: BenefitProgram = {
  id: 'tx-mdcp-2026',
  name: 'Texas MDCP (Medically Dependent Children Program)',
  shortName: 'TX MDCP',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Respite care, home modifications, and support for families of medically fragile children ages 0-20',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 26,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.AGE_RANGE,
      field: 'demographic.age',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: 20,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Child must be under 21 years old',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be medically dependent requiring nursing facility level of care',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.BIRTH_CERTIFICATE,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/providers/long-term-care-providers/medically-dependent-children-program-mdcp',
  helplinePhone: '1-877-438-5658',
};

// Texas TxHmL (Texas Home Living)
export const TX_HOME_LIVING: BenefitProgram = {
  id: 'tx-txhml-2026',
  name: 'Texas Home Living (TxHmL)',
  shortName: 'TxHmL',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Day habilitation, respite, and employment assistance for people with intellectual disabilities living at home',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 52,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have an intellectual disability or related condition',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/disability/intellectual-or-developmental-disabilities-idd-services',
  helplinePhone: '1-877-438-5658',
};

// Texas ABLE Account
export const TX_ABLE: BenefitProgram = {
  id: 'tx-able-2026',
  name: 'Texas ABLE Account',
  shortName: 'TX ABLE',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Tax-advantaged savings account for disability expenses without losing SSI or Medicaid benefits (save up to $19,000/year)',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 1,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have disability that began before age 26 (age 46 starting Jan 2026)',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://www.texasable.org/',
  helplinePhone: '844-489-2253',
};

// Texas Children's Autism Program
export const TX_AUTISM_PROGRAM: BenefitProgram = {
  id: 'tx-autism-2026',
  name: 'Texas Children\'s Autism Program',
  shortName: 'TX Autism Program',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free Applied Behavioral Analysis (ABA) therapy for children ages 3-15 with autism (up to 180 hours/year)',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 8,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.AGE_RANGE,
      field: 'demographic.age',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: 15,
      weight: 0.9,
      isMandatory: false,
      failureMessage: 'Child must be between 3 and 15 years old',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have documented autism spectrum diagnosis',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/disability/childrens-autism-program',
  helplinePhone: '1-800-252-8014',
};

// Texas Community Attendant Services (CAS)
export const TX_COMMUNITY_ATTENDANT: BenefitProgram = {
  id: 'tx-cas-2026',
  name: 'Texas Community Attendant Services',
  shortName: 'TX CAS',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Personal care assistance at home with bathing, dressing, meals, and daily activities',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 8,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have disability requiring assistance with daily living',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.needsAssistance',
      operator: RuleOperator.INCLUDES,
      value: [AssistanceLevel.SOME, AssistanceLevel.EXTENSIVE],
      weight: 0.9,
      isMandatory: true,
      failureMessage: 'Must need assistance with activities of daily living',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/aging/long-term-care',
  helplinePhone: '1-800-252-9240',
};

// Texas Primary Home Care
export const TX_PRIMARY_HOME_CARE: BenefitProgram = {
  id: 'tx-phc-2026',
  name: 'Texas Primary Home Care',
  shortName: 'TX PHC',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'In-home supervision and personal care for elderly and disabled Texans who need help to remain at home',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 6,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 0.8,
      isMandatory: false,
      failureMessage: 'Must be elderly or have a disability',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 300),
      weight: 0.8,
      isMandatory: true,
      failureMessage: 'Income must meet Texas community care guidelines',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/aging/long-term-care',
  helplinePhone: '1-800-252-9240',
};

// Texas PACE (Program of All-Inclusive Care for the Elderly)
export const TX_PACE: BenefitProgram = {
  id: 'tx-pace-2026',
  name: 'Texas PACE (Program of All-Inclusive Care for Elderly)',
  shortName: 'TX PACE',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Comprehensive medical care, adult day care, transportation, and social services for nursing-home-eligible seniors',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 8,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must live in a PACE service area in Texas',
    },
    {
      type: RuleType.AGE_RANGE,
      field: 'demographic.age',
      operator: RuleOperator.GREATER_THAN_OR_EQUAL,
      value: 55,
      weight: 0.9,
      isMandatory: true,
      failureMessage: 'Must be 55 years or older',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.needsAssistance',
      operator: RuleOperator.INCLUDES,
      value: [AssistanceLevel.SOME, AssistanceLevel.EXTENSIVE],
      weight: 0.8,
      isMandatory: true,
      failureMessage: 'Must need nursing home level of care',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/aging/long-term-care/pace',
  helplinePhone: '1-800-252-9240',
};

// Texas Blind Services
export const TX_BLIND_SERVICES: BenefitProgram = {
  id: 'tx-blind-2026',
  name: 'Texas Blind and Visually Impaired Services',
  shortName: 'TX Blind Services',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Orientation and mobility training, adaptive technology, independent living skills for blind Texans',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 4,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be legally blind or visually impaired',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
  ],
  applicationUrl: 'https://www.hhs.texas.gov/services/disability/blind-visually-impaired',
  helplinePhone: '1-800-628-5115',
};

// Texas 2-1-1 Resource Line
export const TX_211: BenefitProgram = {
  id: 'tx-211-2026',
  name: 'Texas 2-1-1 (Free Resource Navigation)',
  shortName: 'TX 2-1-1',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free 24/7 helpline connecting Texans to local assistance with food, housing, utilities, healthcare, and more',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 0,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
  ],
  requiredDocuments: [],
  applicationUrl: 'https://www.211texas.org/',
  helplinePhone: '2-1-1',
};

// Texas Veterans Property Tax Exemption
export const TX_VET_PROPERTY_TAX: BenefitProgram = {
  id: 'tx-vet-property-2026',
  name: 'Texas Veterans Property Tax Exemption',
  shortName: 'TX Vet Property Tax',
  category: BenefitCategory.HOUSING,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Property tax reduction or full exemption for disabled veterans (100% disability = full exemption, saves $6,000+/year)',
  estimatedMonthlyValue: 500,
  processingTimeWeeks: 4,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.isVeteran',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a military veteran',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 0.9,
      isMandatory: false,
      failureMessage: 'Must have service-connected disability rating',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://comptroller.texas.gov/taxes/property-tax/exemptions/disabled-veteran-100-background.php',
  helplinePhone: '1-800-252-5555',
};

// Texas Hazlewood Act (Education)
export const TX_HAZLEWOOD: BenefitProgram = {
  id: 'tx-hazlewood-2026',
  name: 'Texas Hazlewood Act (Education Benefits)',
  shortName: 'TX Hazlewood',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free tuition at Texas public colleges (150 credit hours) for veterans and eligible dependents',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 6,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.isVeteran',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 0.9,
      isMandatory: false,
      failureMessage: 'Must be a veteran or dependent of 100% disabled veteran',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
  ],
  applicationUrl: 'https://www.tvc.texas.gov/education/hazlewood/',
  helplinePhone: '1-877-898-3833',
};

// Texas Veterans Driver License
export const TX_VET_DL: BenefitProgram = {
  id: 'tx-vet-dl-2026',
  name: 'Texas Veterans Free Driver License',
  shortName: 'TX Vet DL',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free Texas driver license or ID card for veterans with 60%+ disability rating',
  estimatedMonthlyValue: 5,
  processingTimeWeeks: 1,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.isVeteran',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a military veteran',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have 60%+ VA disability rating',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://www.dps.texas.gov/section/driver-license/military-service-members',
  helplinePhone: '1-512-424-2600',
};

// Texas Parklands Passport
export const TX_PARKLANDS_PASSPORT: BenefitProgram = {
  id: 'tx-parklands-2026',
  name: 'Texas Parklands Passport',
  shortName: 'TX Parks Pass',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free lifetime entry to all Texas state parks for veterans with 60%+ disability',
  estimatedMonthlyValue: 10,
  processingTimeWeeks: 2,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.isVeteran',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a U.S. veteran',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have 60%+ VA service-connected disability',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.DISABILITY_DETERMINATION,
  ],
  applicationUrl: 'https://tpwd.texas.gov/state-parks/park-information/passes/texas-parklands-passport',
  helplinePhone: '1-512-389-8900',
};

// Texas TBRA (Tenant-Based Rental Assistance)
export const TX_TBRA: BenefitProgram = {
  id: 'tx-tbra-2026',
  name: 'Texas Tenant-Based Rental Assistance',
  shortName: 'TX TBRA',
  category: BenefitCategory.HOUSING,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Rental assistance for up to 5 years for low-income Texans (no time limit for persons with disabilities)',
  estimatedMonthlyValue: 700,
  processingTimeWeeks: 8,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 200),
      weight: 0.9,
      isMandatory: true,
      failureMessage: 'Income must be at or below 80% Area Median Income',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 0.5,
      isMandatory: false,
      failureMessage: 'Persons with disabilities may have extended assistance period',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.PROOF_OF_INCOME,
    DocumentType.LEASE_AGREEMENT,
  ],
  applicationUrl: 'https://www.tdhca.texas.gov/programs/tenant-based-rental-assistance-tbra-program',
  helplinePhone: '1-800-525-0657',
};

// Texas Project Access
export const TX_PROJECT_ACCESS: BenefitProgram = {
  id: 'tx-project-access-2026',
  name: 'Texas Project Access (Section 8 for Transitions)',
  shortName: 'TX Project Access',
  category: BenefitCategory.HOUSING,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Section 8 vouchers to help people with disabilities transition from institutions to community living',
  estimatedMonthlyValue: 800,
  processingTimeWeeks: 12,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have a disability',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 200),
      weight: 0.8,
      isMandatory: true,
      failureMessage: 'Income must meet HUD very low income limits',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.tdhca.texas.gov/project-access',
  helplinePhone: '1-800-525-0657',
};

// Texas Medicaid Buy-In for Working Adults with Disabilities
export const TX_MEDICAID_BUY_IN: BenefitProgram = {
  id: 'tx-medicaid-buy-in-2026',
  name: 'Texas Medicaid Buy-In (Working Adults with Disabilities)',
  shortName: 'TX Medicaid Buy-In',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Medicaid coverage for working adults with disabilities who earn too much for regular Medicaid',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 6,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must have a disability',
    },
    {
      type: RuleType.AGE_RANGE,
      field: 'demographic.age',
      operator: RuleOperator.GREATER_THAN_OR_EQUAL,
      value: 16,
      weight: 0.8,
      isMandatory: true,
      failureMessage: 'Must be age 16-64 and employed',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 250),
      weight: 0.7,
      isMandatory: false,
      failureMessage: 'Income limits apply based on earnings',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.MEDICAL_RECORDS,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.yourtexasbenefits.com/',
  helplinePhone: '1-800-252-8263',
};

// Texas Veterans Mental Health Services
export const TX_VET_MENTAL_HEALTH: BenefitProgram = {
  id: 'tx-vet-mental-health-2026',
  name: 'Texas Veterans Mental Health Services',
  shortName: 'TX Vet Mental Health',
  category: BenefitCategory.HEALTHCARE,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free mental health services, peer support, and crisis intervention for Texas veterans',
  estimatedMonthlyValue: 'varies',
  processingTimeWeeks: 1,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.isVeteran',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a military veteran',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
  ],
  applicationUrl: 'https://www.tvc.texas.gov/mental-health/',
  helplinePhone: '1-800-273-8255',
};

// Texas Fund for Veterans Assistance
export const TX_FUND_VET_ASSISTANCE: BenefitProgram = {
  id: 'tx-fva-2026',
  name: 'Texas Fund for Veterans\' Assistance',
  shortName: 'TX FVA',
  category: BenefitCategory.INCOME,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Emergency financial assistance for rent, utilities, food, and transportation for veterans in need',
  estimatedMonthlyValue: 500,
  processingTimeWeeks: 2,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.CATEGORICAL,
      field: 'demographic.isVeteran',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a veteran or family member',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 200),
      weight: 0.7,
      isMandatory: false,
      failureMessage: 'Emergency assistance based on need',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.tvc.texas.gov/grants/fund-for-veterans-assistance/',
  helplinePhone: '1-877-898-3833',
};

// Texas Weatherization Assistance Program
export const TX_WEATHERIZATION: BenefitProgram = {
  id: 'tx-weatherization-2026',
  name: 'Texas Weatherization Assistance Program',
  shortName: 'TX Weatherization',
  category: BenefitCategory.UTILITIES,
  jurisdiction: 'state',
  jurisdictionCode: 'TX',
  description: 'Free home improvements (insulation, sealing, HVAC) to reduce energy costs for low-income households',
  estimatedMonthlyValue: 100,
  processingTimeWeeks: 12,
  rules: [
    {
      type: RuleType.GEOGRAPHY_MATCH,
      field: 'geography.state',
      operator: RuleOperator.EQUALS,
      value: 'TX',
      weight: 1.0,
      isMandatory: true,
      failureMessage: 'Must be a Texas resident',
    },
    {
      type: RuleType.INCOME_THRESHOLD,
      field: 'financial.monthlyIncome',
      operator: RuleOperator.LESS_THAN_OR_EQUAL,
      value: getMonthlyFPL(1, 200),
      weight: 0.9,
      isMandatory: true,
      failureMessage: 'Income must be at or below 200% of federal poverty level',
    },
    {
      type: RuleType.DISABILITY_REQUIRED,
      field: 'disability.hasDisability',
      operator: RuleOperator.EQUALS,
      value: true,
      weight: 0.4,
      isMandatory: false,
      failureMessage: 'Priority given to elderly and disabled households',
    },
  ],
  requiredDocuments: [
    DocumentType.ID_CARD,
    DocumentType.PROOF_OF_INCOME,
  ],
  applicationUrl: 'https://www.tdhca.texas.gov/weatherization-assistance-program',
  helplinePhone: '1-800-525-0657',
};
