/**
 * Generates a self-contained HTML Benefits Letter document.
 * Opens in a new window for print-to-PDF. No external dependencies.
 */

import { EligibilityResult } from '@/types/benefit';
import { QuizData } from '@/types/quiz';
import { formatCurrency, formatTimeline } from './format';

export function generateBenefitsLetter(results: EligibilityResult[], quizData: QuizData) {
  const eligible = results.filter(r => r.isEligible);
  const possible = results.filter(r => !r.isEligible && r.probability >= 40);
  const totalMonthly = eligible.reduce((sum, r) => sum + r.estimatedMonthlyBenefit, 0);
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Benefits Eligibility Letter — CareNavigator</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #1a1a1a; line-height: 1.5; padding: 40px; max-width: 800px; margin: 0 auto; font-size: 11pt; }
  .header { border-bottom: 2px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { font-size: 20pt; font-weight: 600; letter-spacing: -0.02em; }
  .header p { color: #666; font-size: 10pt; margin-top: 4px; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 24px; font-size: 10pt; color: #444; }
  .section { margin-bottom: 24px; }
  .section-title { font-size: 12pt; font-weight: 600; margin-bottom: 8px; padding-bottom: 4px; border-bottom: 1px solid #e5e5e5; }
  .profile-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 24px; font-size: 10pt; }
  .profile-grid dt { color: #666; }
  .profile-grid dd { font-weight: 500; }
  .summary-box { background: #f5f5f5; border-radius: 8px; padding: 16px; display: flex; gap: 32px; margin-bottom: 24px; }
  .summary-stat { text-align: center; }
  .summary-stat .num { font-size: 24pt; font-weight: 700; line-height: 1; }
  .summary-stat .label { font-size: 9pt; color: #666; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; font-size: 10pt; margin-bottom: 8px; }
  th { text-align: left; padding: 6px 8px; background: #f5f5f5; font-weight: 600; border-bottom: 1px solid #ddd; }
  td { padding: 6px 8px; border-bottom: 1px solid #eee; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .match-high { color: #16a34a; font-weight: 600; }
  .match-mid { color: #ca8a04; font-weight: 600; }
  .match-low { color: #999; }
  .program-detail { margin-bottom: 20px; page-break-inside: avoid; }
  .program-detail h3 { font-size: 11pt; font-weight: 600; margin-bottom: 4px; }
  .program-detail .meta-line { font-size: 9pt; color: #666; margin-bottom: 6px; }
  .program-detail .details { font-size: 10pt; }
  .program-detail .docs { margin-top: 6px; }
  .program-detail .docs span { display: inline-block; background: #f0f0f0; padding: 1px 6px; border-radius: 3px; font-size: 9pt; margin: 1px 2px; }
  .checklist { list-style: none; padding: 0; }
  .checklist li { padding: 3px 0; font-size: 10pt; }
  .checklist li::before { content: "☐ "; color: #999; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 9pt; color: #888; }
  .page-break { page-break-before: always; }
  @media print {
    body { padding: 0; }
    .no-print { display: none; }
  }
</style>
</head>
<body>

<div class="no-print" style="background:#fffbeb;border:1px solid #fbbf24;border-radius:8px;padding:12px 16px;margin-bottom:24px;font-size:10pt;color:#92400e;">
  Press <strong>Ctrl+P</strong> (or <strong>⌘+P</strong>) to save as PDF. Select "Save as PDF" as the destination.
</div>

<div class="header">
  <h1>Benefits Eligibility Letter</h1>
  <p>Generated by CareNavigator on ${date}</p>
</div>

<div class="section">
  <div class="section-title">Applicant Profile</div>
  <dl class="profile-grid">
    <dt>Location</dt><dd>${quizData.geography.state}, ${quizData.geography.county} County (${quizData.geography.zipCode})</dd>
    <dt>Residency</dt><dd>${quizData.geography.residencyMonths} months</dd>
    <dt>Age</dt><dd>${quizData.demographic.age}</dd>
    <dt>Household Size</dt><dd>${quizData.demographic.householdSize}</dd>
    <dt>Monthly Income</dt><dd>${formatCurrency(quizData.financial.monthlyIncome)}</dd>
    <dt>Countable Assets</dt><dd>${formatCurrency(quizData.financial.countableAssets)}</dd>
    <dt>Disability</dt><dd>${quizData.disability.hasDisability ? 'Yes' : 'No'}</dd>
    <dt>Veteran</dt><dd>${quizData.demographic.isVeteran ? 'Yes' : 'No'}</dd>
    <dt>Receiving SSI</dt><dd>${quizData.disability.receivingSSI ? 'Yes' : 'No'}</dd>
    <dt>Receiving SSDI</dt><dd>${quizData.disability.receivingSSDI ? 'Yes' : 'No'}</dd>
  </dl>
</div>

<div class="summary-box">
  <div class="summary-stat"><div class="num">${eligible.length}</div><div class="label">Likely Eligible</div></div>
  <div class="summary-stat"><div class="num">${possible.length}</div><div class="label">Possibly Eligible</div></div>
  <div class="summary-stat"><div class="num">${totalMonthly > 0 ? formatCurrency(totalMonthly) : 'Varies'}</div><div class="label">Est. Monthly Value</div></div>
  <div class="summary-stat"><div class="num">${results.length}</div><div class="label">Programs Evaluated</div></div>
</div>

<div class="section">
  <div class="section-title">Eligibility Summary</div>
  <table>
    <thead><tr><th>Program</th><th>Category</th><th>Match</th><th>Est. Value</th><th>Timeline</th></tr></thead>
    <tbody>
${results.filter(r => r.probability > 0).map(r => `      <tr>
        <td>${r.program.name}</td>
        <td>${r.program.category}</td>
        <td class="${r.probability >= 70 ? 'match-high' : r.probability >= 40 ? 'match-mid' : 'match-low'}">${r.probability}%</td>
        <td>${r.estimatedMonthlyBenefit > 0 ? formatCurrency(r.estimatedMonthlyBenefit) + '/mo' : 'Varies'}</td>
        <td>${formatTimeline(r.timelineWeeks)}</td>
      </tr>`).join('\n')}
    </tbody>
  </table>
</div>

${eligible.length > 0 ? `
<div class="page-break"></div>
<div class="section">
  <div class="section-title">Recommended Programs — Detailed</div>
${eligible.map((r, i) => `
  <div class="program-detail">
    <h3>${i + 1}. ${r.program.name}</h3>
    <div class="meta-line">${r.program.category} · ${r.probability}% match · ${r.estimatedMonthlyBenefit > 0 ? formatCurrency(r.estimatedMonthlyBenefit) + '/mo' : 'Varies'} · ${formatTimeline(r.timelineWeeks)}</div>
    <div class="details">
      <p>${r.program.description}</p>
      ${r.reasoning?.whyEligible?.length ? `<p style="margin-top:4px;color:#16a34a;">${r.reasoning.whyEligible.join(' ')}</p>` : ''}
      ${r.program.requiredDocuments.length > 0 ? `<div class="docs"><strong>Documents needed:</strong> ${r.program.requiredDocuments.map(d => `<span>${d.replace(/_/g, ' ')}</span>`).join(' ')}</div>` : ''}
      ${r.program.applicationUrl && r.program.applicationUrl !== '#' ? `<p style="margin-top:4px;font-size:9pt;">Apply: ${r.program.applicationUrl}</p>` : ''}
      ${r.program.helplinePhone ? `<p style="font-size:9pt;">Helpline: ${r.program.helplinePhone}</p>` : ''}
    </div>
  </div>
`).join('')}
</div>
` : ''}

${possible.length > 0 ? `
<div class="section">
  <div class="section-title">Possibly Eligible — Worth Investigating</div>
${possible.slice(0, 10).map((r, i) => `
  <div class="program-detail">
    <h3>${r.program.name} <span style="color:#ca8a04;font-size:9pt;">(${r.probability}% match)</span></h3>
    <div class="meta-line">${r.program.description}</div>
    ${r.failedRules.length > 0 ? `<p style="font-size:9pt;color:#666;">Issues: ${r.failedRules.map(f => f.message).join('; ')}</p>` : ''}
  </div>
`).join('')}
</div>
` : ''}

<div class="section">
  <div class="section-title">Application Checklist</div>
  <ul class="checklist">
    <li>Gather all required identification documents (ID, Social Security card)</li>
    <li>Collect proof of income (pay stubs, SSI/SSDI award letters, tax returns)</li>
    <li>Prepare proof of residency (utility bill, lease agreement)</li>
    <li>Obtain medical documentation if applying for disability programs</li>
    ${eligible.map(r => `<li>Apply for ${r.program.name}${r.program.applicationUrl && r.program.applicationUrl !== '#' ? ` — ${r.program.applicationUrl}` : ''}</li>`).join('\n    ')}
    <li>Call 2-1-1 for free assistance with applications</li>
  </ul>
</div>

<div class="footer">
  <p><strong>Disclaimer:</strong> This letter is a preliminary eligibility estimate generated by CareNavigator based on self-reported information.
  Final eligibility will be determined by the administering agencies upon application review. This document is not a guarantee of benefits.</p>
  <p style="margin-top:8px;">Generated ${date} · CareNavigator · care-navigator.pages.dev</p>
</div>

</body>
</html>`;

  return html;
}

export function openBenefitsLetter(results: EligibilityResult[], quizData: QuizData) {
  const html = generateBenefitsLetter(results, quizData);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, '_blank');
  // Clean up after a delay
  setTimeout(() => URL.revokeObjectURL(url), 60000);
  return win;
}
